### ISSUE TITLE
bug: Will generate a component instance no matter what the condition is

### ISSUE THREAD

**Issue by IanDxSSXX** [romac/react-if#242] opened 2023-01-12 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

 Will generate a component instance no matter what the condition is

### Steps To Reproduce

<img width="585" alt="image" src="https://user-images.githubusercontent.com/69476139/212028407-3cc12357-66bb-4e89-9022-c4be0e35c83d.png">
<img width="328" alt="image" src="https://user-images.githubusercontent.com/69476139/212028469-1dace853-68a0-415b-96fe-618083c72d41.png">

### Expected behavior

It costs to much, you should just use a function to wrap to to prevent the instance generation.

**Comment by favna** [comment] 2023-01-12 18:45
This is by design and can be addressed by delaying evaluation of children as described in the README: https://github.com/romac/react-if#delaying-evaluation-of-children--condition

**Comment by favna** [comment] 2023-06-29 18:52
Closing this as not planned

**Closed by favna** 2023-06-29 18:52 UTC
Labels: wontfix
